### ISSUE TITLE
Empty line whitespace doesn't seem to be caught

### ISSUE THREAD

**Issue by ghollingworth** [yifu/highlight-trailing-whitespaces#1]
Just installed 0.0.1 on VSC and had an empty line that had white space only

This was not highlighted

**Comment by yifu** [comment]
Hi @ghollingworth , thank you for taking the time to install my plugin and actually test it! :-)

Concerning the issue you raised: when I developed the plugin, I wanted it to never highlight empty lines. That was in order to get the same results as an emacs mode I use, which behaves that way.

At least when you're writing such thing:

```
function toto() {
    let a = 3;

    if (a < 10) {
        // do some stuf
    }
}
```

Then in the example above the empty line between `let a = 3` and the if statement won't get highlighted when it contains empty spaces. Well... From my memory.

Were you expecting another behavior?

**Comment by ghollingworth** [comment]
That's not the behaviour you get from git diff it will highlight any end of
line whitespace

Gordon

On 25 Jul 2016 10:17 p.m., "Yves Baumes" notifications@github.com wrote:

Hi @ghollingworth https://github.com/ghollingworth , thank you for taking
the time to install my plugin and actually test it! :-)

Concerning the issue you raised: when I developed the plugin, I wanted it
to never highlight empty lines. That was in order to get the same results
as an emacs mode I use, which behaves that way.

At least when you're writing such thing:

function toto() {
    let a = 3;

```
if (a < 10) {
    // do some stuf
}
```

}

Then in the example above the empty line between let a = 3 and the if
statement won't get highlighted when it contains empty spaces. Well... From
my memory.

Were you expecting another behavior?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/yifu/highlight-trailing-whitespaces/issues/1#issuecomment-235088147,
or mute the thread

**Comment by yifu** [comment]
Ok I've fixed this. You should find the newest version (0.0.2) on the vscode market place.

**Comment by ghollingworth** [comment]
Thanks, will test later today
